// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250805165310_UppdatePictureName")]
    partial class UppdatePictureName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Games", b =>
                {
                    b.Property<long>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("GameId"));

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GameDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GameGenre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GameTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("GamesCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("GameId");

                    b.HasIndex("GamesCategoryId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1L,
                            Developer = "ConcernedApe",
                            GameDescription = "A farming simulation game where you can grow crops, raise animals, and build your farm.",
                            GameGenre = "Indie Games",
                            GameTitle = "Stardew Valley",
                            GamesCategoryId = 3L,
                            ImageUrl = "img/StardewValley.jpg",
                            Price = 13.99m,
                            ReleaseDate = new DateTime(2016, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GameId = 5L,
                            Developer = "Playdead",
                            GameDescription = "A puzzle-platformer adventure game with a dark, atmospheric world and unique art style.",
                            GameGenre = "Indie Games",
                            GameTitle = "Limbo",
                            GamesCategoryId = 3L,
                            ImageUrl = "img/Limbo.jpg",
                            Price = 9.99m,
                            ReleaseDate = new DateTime(2010, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GameId = 6L,
                            Developer = "Re-Logic",
                            GameDescription = "A 2D sandbox adventure game where you can explore, build, and fight in a procedurally generated world.",
                            GameGenre = "Indie Games",
                            GameTitle = "Terraria",
                            GamesCategoryId = 3L,
                            ImageUrl = "img/Terraria.jpg",
                            Price = 9.75m,
                            ReleaseDate = new DateTime(2011, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GameId = 3L,
                            Developer = "FromSoftware",
                            GameDescription = "An action RPG set in a dark fantasy world, known for its challenging gameplay and deep lore.",
                            GameGenre = "RPG",
                            GameTitle = "Elden ring",
                            GamesCategoryId = 1L,
                            ImageUrl = "img/EldenRing.jpg",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GameId = 4L,
                            Developer = "CD Projekt Red",
                            GameDescription = "A futuristic open-world RPG set in the dystopian Night City, focusing on a customizable character.",
                            GameGenre = "RPG",
                            GameTitle = "Cyberpunk 2077",
                            GamesCategoryId = 1L,
                            ImageUrl = "img/cyberpunk.jpg",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GameId = 2L,
                            Developer = "Rockstar Games",
                            GameDescription = "An action-adventure game set in the American Wild West, focusing on the life of an outlaw.",
                            GameGenre = "Action",
                            GameTitle = "Red Dead Redemption 2",
                            GamesCategoryId = 2L,
                            ImageUrl = "img/RDR2.jpg",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GameId = 7L,
                            Developer = "Respawn Entertainment",
                            GameDescription = "A free-to-play battle royale game set in the Titanfall universe, featuring unique characters with special abilities.",
                            GameGenre = "Action",
                            GameTitle = "Apex Legends",
                            GamesCategoryId = 2L,
                            ImageUrl = "img/ApexLedgens.jpg",
                            Price = 0.00m,
                            ReleaseDate = new DateTime(2019, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GameId = 8L,
                            Developer = "Crystal Dynamics",
                            GameDescription = "An action-adventure game that follows the origin story of Lara Croft as she explores a mysterious island.",
                            GameGenre = "Action",
                            GameTitle = "Tomb Raider (2013)",
                            GamesCategoryId = 2L,
                            ImageUrl = "img/TombRaider.jpg",
                            Price = 14.99m,
                            ReleaseDate = new DateTime(2013, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GameId = 9L,
                            Developer = "Maxis",
                            GameDescription = "A life simulation game where players create and control people in a virtual world.",
                            GameGenre = "Simulation",
                            GameTitle = "The Sims 4",
                            GamesCategoryId = 4L,
                            ImageUrl = "img/TheSims4.jpg",
                            Price = 0.00m,
                            ReleaseDate = new DateTime(2014, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GameId = 10L,
                            Developer = "SCS Software",
                            GameDescription = "A vehicle simulation game where players drive trucks across Europe, delivering cargo and managing their own trucking company.",
                            GameGenre = "Simulation",
                            GameTitle = "Euro Truck Simulator 2",
                            GamesCategoryId = 4L,
                            ImageUrl = "img/EuroTruckSimulator2.jpg",
                            Price = 19.99m,
                            ReleaseDate = new DateTime(2012, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GameId = 11L,
                            Developer = "GIANTS Software",
                            GameDescription = "A farming simulation game that allows players to manage their own farm, grow crops, and raise animals.",
                            GameGenre = "Simulation",
                            GameTitle = "Farming Simulator 25",
                            GamesCategoryId = 4L,
                            ImageUrl = "img/FarmingSimulator25.jpg",
                            Price = 49.99m,
                            ReleaseDate = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Backend.Models.GamesCategory", b =>
                {
                    b.Property<long>("GamesCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("GamesCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("GamesCategoryId");

                    b.ToTable("GamesCategories");

                    b.HasData(
                        new
                        {
                            GamesCategoryId = 1L,
                            CategoryName = "RPG"
                        },
                        new
                        {
                            GamesCategoryId = 2L,
                            CategoryName = "Action"
                        },
                        new
                        {
                            GamesCategoryId = 3L,
                            CategoryName = "Indie games"
                        },
                        new
                        {
                            GamesCategoryId = 4L,
                            CategoryName = "Simulation"
                        });
                });

            modelBuilder.Entity("Backend.Models.Games", b =>
                {
                    b.HasOne("Backend.Models.GamesCategory", "GamesCategory")
                        .WithMany("Games")
                        .HasForeignKey("GamesCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GamesCategory");
                });

            modelBuilder.Entity("Backend.Models.GamesCategory", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
